import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Hero from '@/components/Hero'
import Slider from '@/components/Slider'
import { SliderData } from '@/components/SliderData'
import Instagram from '@/components/Instagram'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Responsive Next-Tailwind Css</title>
        <meta name='description' content='Generated by create next app' />
        <link ref='icon' href='/favicon.ico' />
      </Head>
      <Hero heading="Captur Photography" message="I capture movements in nature and keep them alive." />
      <Slider slides={SliderData} />
      <Instagram />
    </div> 
  )
}
